version: "3.9"

services:
  adminer:
    container_name: adminer
    image: adminer
    restart: on-failure
    environment:
      - ADMINER_DESIGN=pepa-linha
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - network

  database:
    image: postgres:16.3-alpine
    restart: always
    container_name: database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./backend:/app
    command: sh -c "composer install && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"
    env_file:
      - ./backend/.env
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  database_data:
