services:
  adminer:
    container_name: adminer
    image: adminer
    restart: on-failure
    environment:
      - ADMINER_DESIGN=pepa-linha
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - network

  database:
    image: postgres:16.3-alpine
    restart: always
    container_name: database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - database
    volumes:
      - ./backend:/app
    command: sh -c "composer install && php artisan migrate && php artisan serve --host=0.0.0.0 --port=80"
    env_file:
      - ./backend/.env
    networks:
      - network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - network

  stripe:
    container_name: stripe
    build:
      context: ./backend/stripe
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - stripe-gpg://root/.gnupg/
      - stripe-pass://root/.password-store/
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  database_data:
  stripe-gpg:
  stripe-pass:
